version: "3"

services:
  mongo:
    image: "mongo:5.0.9"
    restart: always
    volumes:
      - ".docker-data/mongo:/data/db"
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  postgres:
    image: "postgres:14.4"
    restart: always
    volumes:
      - ".docker-data/postgres:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
